- platform: afvalbeheer
  disableicons: 1
  dutch: 1
  postcode: !secret afvalbeheer_zipcode
  streetname: !secret afvalbeheer_streetname
  streetnumber: !secret afvalbeheer_streetnumber
  wastecollector: RecycleApp
  upcomingsensor: 1
  resources:
    - gft
    - papier
    - pmd
    - restafval