- id: '1624892715828'
  alias: verlichting - berging - aan - beweging en lux onder 60, uit na 20 seconden
  description: Verlichting activeren bij beweging in de berging, onder 60 lux, uitschakelen
    na 20 seconden geen beweging
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hue_motion_sensor_berging
      light_target:
        entity_id: light.lamp_berging
      no_motion_wait: 20
      motion_entity_lux: 60
      motion_entity_lux_meter: sensor.hue_motion_sensor_berging_light_level
- id: '1625850309627'
  alias: verlichting - voorgevel - aan - 20 minuten na zonsondergang
  description: ''
  use_blueprint:
    path: lights_on_sunset.yaml
    input:
      light_target:
        entity_id:
        - light.lamp_voorgevel
      offset_time: 00:20:00
- id: '1625939645313'
  alias: verlichting - toilet - aan - beweging en lux onder 50, uit na 120 seconden
  description: ''
  use_blueprint:
    path: motion_light_lux_detection.yaml
    input:
      motion_entity_lux: 50
      no_motion_wait: 120
      motion_entity: binary_sensor.hue_motion_sensor_2_motion
      light_target:
        entity_id: light.lamp_toilet
      motion_entity_lux_meter: sensor.hue_motion_sensor_2_light_level
- id: '1628975132600'
  alias: verlichting - staanlamp - aan - zonsondergang
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.stopcontact_woonkamer_rechts
  mode: single
- id: '1636644968422'
  alias: verlichting - zijtuin - aan - 20 minuten na zonsondergang
  description: ''
  use_blueprint:
    path: lights_on_sunset.yaml
    input:
      light_target:
        entity_id:
        - light.lamp_zijtuin
      offset_time: 00:20:00
- id: '1640524642103'
  alias: Alert - weer - Meteoalarm
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.meteoalarm
    from: 'off'
  action:
  - service: notify.mobile_app_iphone_van_sara
    data:
      title: '{{state_attr(''binary_sensor.meteoalarm'', ''headline'')}}'
      message: '{{state_attr(''binary_sensor.meteoalarm'', ''description'')}} vanaf
        {{state_attr(''binary_sensor.meteoalarm'', ''effective'')}}'
  - service: notify.mobile_app_iphone_van_tom2
    data:
      title: '{{state_attr(''binary_sensor.meteoalarm'', ''headline'')}}'
      message: '{{state_attr(''binary_sensor.meteoalarm'', ''description'')}} vanaf
        {{state_attr(''binary_sensor.meteoalarm'', ''effective'')}}'
  mode: single
- id: '1640555237856'
  alias: verlichting - slaapkamer - aan - fade-in op werkdagen
  description: ''
  trigger:
  - platform: time
    at: input_datetime.wake_up_time
  condition:
  - condition: state
    entity_id: input_boolean.wake_up_light
    state: 'on'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    target:
      entity_id: script.fade_in_slaapkamerverlichting
  mode: single
- id: '1640677987104'
  alias: Garbage collection notifications
  description: ''
  trigger:
  - platform: time
    at: '20:30'
  condition:
  - condition: template
    value_template: '{{ states.sensor.recycleapp_morgen.state != "Geen" }}'
  action:
  - service: notify.mobile_app_iphone_8_tom
    data:
      title: ♻️ Afvalophaling
      message: Morgen ophaling van {{ states.sensor.recycleapp_morgen.state }}
  - service: notify.mobile_app_iphone_van_sara
    data:
      title: ♻️ Afvalophaling
      message: Morgen ophaling van {{ states.sensor.recycleapp_morgen.state }}
  mode: single
- id: '1641201231964'
  alias: Turn outside lights off based on input datetime
  description: ''
  use_blueprint:
    path: lights_off_based_on_input_datetime.yaml
    input:
      time_entity: input_datetime.outside_lights_off_time
      light_target:
        area_id: buiten
- id: '1641284191881'
  alias: Lighting - presence simulation - lights toggle
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: sun
    after: sunset
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  - condition: time
    before: '23:15'
  action:
  - delay: 00:{{ '{:02}'.format(range(0, 30) | random | int) }}:00
  - service: homeassistant.toggle
    target:
      entity_id: '{{ state_attr(''light.presence_simulation'',''entity_id'') | random
        }}'
  mode: single
- id: '1641285136900'
  alias: Lighting - presence simulation - lights off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.end_time_presence_simulation
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  action:
  - service: homeassistant.turn_off
    target:
      entity_id:
      - light.presence_simulation
      - switch.stopcontact_woonkamer_rechts
  mode: single
- id: '1641286153723'
  alias: Lighting presence simulation bedroom lights
  description: ''
  trigger:
  - platform: time
    at: input_datetime.end_time_presence_simulation
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  action:
  - service: light.turn_on
    target:
      entity_id: light.master_bedroom_plafond
    data:
      brightness_pct: 20
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.master_bedroom_plafond
  mode: single
- id: '1641406072469'
  alias: Arm alarm if nobody is home
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: home
    to: not_home
  condition: []
  action:
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.alarm
  mode: single
- id: '1641406355882'
  alias: Trigger alarm on motion detected when alarm is armed
  description: ''
  trigger:
  - platform: state
    entity_id: group.motion_sensors
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.home_alarm
  mode: single
- id: '1641407101821'
  alias: Send notification when alarm is triggered
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: triggered
  condition: []
  action:
  - service: notify.notify
    data:
      title: Alarm
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
      message: Er is beweging gedetecteerd in huis!
  mode: single
- id: '1641459697562'
  alias: Shut down alarm when the family is home
  description: ''
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
  condition: []
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.alarm
  mode: single
- id: '1642971842503'
  alias: verlichting - slaapkamer - aan - fade-in op weekends / niet-werkdagen
  description: ''
  trigger:
  - platform: time
    at: input_datetime.wake_up_time_weekend
  condition:
  - condition: state
    entity_id: input_boolean.wake_up_light
    state: 'on'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    target:
      entity_id: script.fade_in_slaapkamerverlichting
  mode: single
- id: '1658337291271'
  alias: Work - start work countdown timer
  description: ''
  trigger:
  - platform: zone
    entity_id: person.tom
    zone: zone.work_tom
    event: enter
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: timer.workday_countdown
      state: idle
  action:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - choose:
    - conditions:
      - condition: time
        weekday:
        - fri
      sequence:
      - service: timer.start
        data:
          duration: 07:00:00
        target:
          entity_id: timer.workday_countdown
    default:
    - service: timer.start
      data: {}
      target:
        entity_id: timer.workday_countdown
  mode: single
- id: '1658342401317'
  alias: Work - end of day notification
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.workday_countdown
  condition: []
  action:
  - service: notify.mobile_app_iphone_van_tom2
    data:
      title: Werkdag einde
      message: Tijd om te vertrekken. Reistijd is {{ states('sensor.reistijd_naar_huis')
        }} {{ state_attr('sensor.reistijd_naar_huis', 'unit_of_measurement') }}
  mode: single
- id: '1658485901080'
  alias: Save weather forecast next day
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  action:
  - service: input_text.set_value
    data:
      value: '{{ state_attr(''weather.keizershoek'', ''forecast'')[0].condition }}'
    target:
      entity_id: input_text.weather_forecast
  - service: input_number.set_value
    data:
      value: '{{ state_attr(''weather.keizershoek'', ''forecast'')[0].templow | float
        }}'
    target:
      entity_id: input_number.weather_forecast_low_temperature
  - service: input_number.set_value
    data:
      value: '{{ state_attr(''weather.keizershoek'', ''forecast'')[0].temperature
        | float }}'
    target:
      entity_id: input_number.weather_forecast_temperature
  - service: input_number.set_value
    data:
      value: '{{ state_attr(''weather.keizershoek'', ''forecast'')[0].precipitation
        | float }}'
    target:
      entity_id: input_number.weather_forecast_precip
  mode: single
- id: '1658486506108'
  alias: Workday - Morning message
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.vacation
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - service: notify.mobile_app_iphone_van_tom2
    data:
      title: Goeiemorgen
      message: 'Goeiemorgen, het is nu {{ states(''sensor.weather_conditions_dutch'')
        }} en {{ state_attr(''weather.keizershoek'', ''temperature'') }}°C. Reistijd
        naar kantoor is {{ states(''sensor.reistijd_naar_werk'') }} {{ state_attr(''sensor.reistijd_naar_werk'',
        ''unit_of_measurement'') }}.

        Vandaag wordt het {{ states(''sensor.weather_predicted_conditions_dutch'')
        }} met temperaturen tussen {{ states(''input_number.weather_forecast_low_temperature'')
        | round(0) | trim }}°C en {{ states(''input_number.weather_forecast_temperature'')
        | round(0) | trim }}°C met {{ states(''input_number.weather_forecast_precip'')
        | trim }}mm neerslag.

        '
  mode: single
