- id: '1624892715828'
  alias: Verlichting - berging - bewegingsmelder
  description: Verlichting activeren bij beweging in de berging, onder 75 lux, uitschakelen
    na 20 seconden geen beweging
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hue_motion_sensor_berging
      light_target:
        entity_id: light.lamp_berging
      no_motion_wait: 20
      motion_entity_lux: 60
      motion_entity_lux_meter: sensor.hue_motion_sensor_berging_light_level
- id: '1625850309627'
  alias: Verlichting - zijtuin - licht aan bij zonsondergang
  description: ''
  use_blueprint:
    path: lights_on_sunset.yaml
    input:
      light_target:
        entity_id: light.lamp_zijtuin
- id: '1625850347189'
  alias: Verlichting - zijtuin - licht uit om 23:00
  description: ''
  use_blueprint:
    path: lights_off_midnight.yaml
    input:
      light_target:
        entity_id: light.lamp_zijtuin
      turn_off_time: '23:00:00'
