- id: '1624892715828'
  alias: verlichting - berging - aan - beweging en lux onder 60, uit na 20 seconden
  description: Verlichting activeren bij beweging in de berging, onder 60 lux, uitschakelen
    na 20 seconden geen beweging
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.hue_motion_sensor_berging
      light_target:
        entity_id: light.lamp_berging
      no_motion_wait: 20
      motion_entity_lux: 60
      motion_entity_lux_meter: sensor.hue_motion_sensor_berging_light_level
- id: '1625850309627'
  alias: verlichting - voorgevel - aan - 20 minuten na zonsondergang
  description: ''
  use_blueprint:
    path: lights_on_sunset.yaml
    input:
      light_target:
        entity_id:
        - light.lamp_voorgevel
      offset_time: 00:20:00
- id: '1625860388037'
  alias: verlichting - zijtuin en voorgevel - uit - 22:00
  description: ''
  use_blueprint:
    path: lights_off_at_configured_time.yaml
    input:
      light_target:
        entity_id:
        - light.lamp_zijtuin
        - light.lamp_voorgevel
      turn_off_time: '22:00:00'
- id: '1625939645313'
  alias: verlichting - toilet - aan - beweging en lux onder 50, uit na 120 seconden
  description: ''
  use_blueprint:
    path: motion_light_lux_detection.yaml
    input:
      motion_entity_lux: 50
      no_motion_wait: 120
      motion_entity: binary_sensor.hue_motion_sensor_2_motion
      light_target:
        entity_id: light.lamp_toilet
      motion_entity_lux_meter: sensor.hue_motion_sensor_2_light_level
- id: '1628975132600'
  alias: verlichting - staanlamp - aan - zonsondergang
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.stopcontact_woonkamer_rechts
  mode: single
- id: '1636644968422'
  alias: verlichting - zijtuin - aan - 20 minuten na zonsondergang
  description: ''
  use_blueprint:
    path: lights_on_sunset.yaml
    input:
      light_target:
        entity_id:
        - light.lamp_zijtuin
      offset_time: 00:20:00
- id: '1640524642103'
  alias: Alert - weer - Meteoalarm
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.meteoalarm
    from: 'off'
  action:
  - service: notify.notify
    data:
      title: '{{state_attr(''binary_sensor.meteoalarm'', ''headline'')}}'
      message: '{{state_attr(''binary_sensor.meteoalarm'', ''description'')}} vanaf
        {{state_attr(''binary_sensor.meteoalarm'', ''effective'')}}'
  mode: single
- id: '1640555237856'
  alias: verlichting - slaapkamer - aan - fade-in op werkdagen
  description: ''
  trigger:
  - platform: time
    at: input_datetime.wake_up_time
  condition:
  - condition: state
    entity_id: input_boolean.wake_up_light
    state: 'on'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    target:
      entity_id: script.fade_in_slaapkamerverlichting
  mode: single
- id: '1640677987104'
  alias: Garbage collection notifications
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.recycleapp_morgen
  condition:
  - condition: template
    value_template: '{{ states.sensor.recycleapp_morgen.state != ''Geen'' }}'
  action:
  - service: notify.mobile_app_iphone_8_tom
    data:
      title: ♻️ Afvalophaling
      message: Morgen ophaling van {{ states.sensor.recycleapp_morgen.state }}
  mode: single
