- id: '1625850309627'
  alias: verlichting - voorgevel - aan - 20 minuten na zonsondergang
  description: ''
  use_blueprint:
    path: lights_on_sunset.yaml
    input:
      light_target:
        entity_id:
        - light.lamp_voorgevel
      offset_time: 00:20:00
- id: '1628975132600'
  alias: verlichting - vloerlamp - aan - zonsondergang
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:05:00
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.stopcontact_woonkamer_rechts
    data: {}
  mode: single
- id: '1636644968422'
  alias: verlichting - zijtuin - aan - 20 minuten na zonsondergang
  description: ''
  use_blueprint:
    path: lights_on_sunset.yaml
    input:
      light_target:
        entity_id:
        - light.lamp_zijtuin
      offset_time: 00:20:00
- id: '1640524642103'
  alias: Alert - weer - Meteoalarm
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.meteoalarm
    from: 'off'
  action:
  - service: notify.mobile_app_iphone_van_sara
    data:
      title: '{{state_attr(''binary_sensor.meteoalarm'', ''headline'')}}'
      message: '{{state_attr(''binary_sensor.meteoalarm'', ''description'')}} vanaf
        {{state_attr(''binary_sensor.meteoalarm'', ''effective'')}}'
  - service: notify.mobile_app_iphone_van_tom
    data:
      title: '{{state_attr(''binary_sensor.meteoalarm'', ''headline'')}}'
      message: '{{state_attr(''binary_sensor.meteoalarm'', ''description'')}} vanaf
        {{state_attr(''binary_sensor.meteoalarm'', ''effective'')}}'
  mode: single
- id: '1641406355882'
  alias: Trigger alarm on motion detected when alarm is armed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bewegingsmelders
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    target:
      entity_id: alarm_control_panel.alarm
  mode: single
- id: '1641407101821'
  alias: Send notification when alarm is triggered
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: triggered
  condition: []
  action:
  - service: notify.notify
    data:
      title: Alarm
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
      message: Er is beweging gedetecteerd in huis!
  mode: single
- id: '1658486506108'
  alias: notificaties - ochtendbericht (werkdag)
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.vacation
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - service: notify.mobile_app_iphone_van_tom
    data:
      title: Goeiemorgen
      message: 'Goeiemorgen, het is nu {{ states(''sensor.weather_conditions_dutch'')
        }} en {{ state_attr(''weather.keizershoek'', ''temperature'') }}°C. Reistijd
        naar kantoor is {{ states(''sensor.reistijd_naar_werk'') }} {{ state_attr(''sensor.reistijd_naar_werk'',
        ''unit_of_measurement'') }}.

        Vandaag wordt het {{ states(''sensor.weather_predicted_conditions_dutch'')
        }} met temperaturen tussen {{ states(''input_number.weather_forecast_low_temperature'')
        | round(0) | trim }}°C en {{ states(''input_number.weather_forecast_temperature'')
        | round(0) | trim }}°C met {{ states(''input_number.weather_forecast_precip'')
        | trim }}mm neerslag.

        '
  mode: single
- id: '1682009182943'
  alias: verlichting - vloerlamp - uit - 23:45
  description: ''
  trigger:
  - platform: time
    at: '23:45:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.stopcontact_woonkamer_rechts
  mode: single
- id: '1698662220340'
  alias: notificaties - ochtendbericht
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.vacation
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: ff
  action:
  - service: notify.mobile_app_iphone_van_tom
    data:
      title: Goeiemorgen
      message: 'Goeiemorgen, het is nu {{ states(''sensor.weather_conditions_dutch'')
        }} en {{ state_attr(''weather.keizershoek'', ''temperature'') }}°C.

        Vandaag wordt het {{ states(''sensor.weather_predicted_conditions_dutch'')
        }} met temperaturen tussen {{ states(''input_number.weather_forecast_low_temperature'')
        | round(0) | trim }}°C en {{ states(''input_number.weather_forecast_temperature'')
        | round(0) | trim }}°C met {{ states(''input_number.weather_forecast_precip'')
        | trim }}mm neerslag.

        '
  mode: single
- id: '1699120321203'
  alias: Tag - Toiletpapier is gescand
  description: ''
  trigger:
  - platform: tag
    tag_id: a12f63bc-ed7e-4a7a-b360-888742507810
  - platform: event
    event_type: tagscantoiletpapier
  condition: []
  action:
  - service: shopping_list.add_item
    data:
      name: Toiletpapier
  mode: single
- id: '1699881656417'
  alias: Tag - door tag is scanned
  description: ''
  trigger:
  - platform: event
    event_type: tagscandoor
  condition: []
  action:
  - service: '{% if is_state("alarm_control_panel.alarm", "disarmed") %} script.leaving_house
      {% else %} script.coming_home {% endif %}

      '
  mode: single
