- id: '1640524642103'
  alias: Alert - weer - Meteoalarm
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.meteoalarm
    from: 'off'
  action:
  - service: notify.mobile_app_iphone_van_sara
    data:
      title: '{{state_attr(''binary_sensor.meteoalarm'', ''headline'')}}'
      message: '{{state_attr(''binary_sensor.meteoalarm'', ''description'')}} vanaf
        {{state_attr(''binary_sensor.meteoalarm'', ''effective'')}}'
  - service: notify.mobile_app_iphone_van_tom
    data:
      title: '{{state_attr(''binary_sensor.meteoalarm'', ''headline'')}}'
      message: '{{state_attr(''binary_sensor.meteoalarm'', ''description'')}} vanaf
        {{state_attr(''binary_sensor.meteoalarm'', ''effective'')}}'
  mode: single
- id: '1699120321203'
  alias: Tag - Toiletpapier is gescand
  description: ''
  trigger:
  - platform: tag
    tag_id: a12f63bc-ed7e-4a7a-b360-888742507810
  - platform: event
    event_type: tagscantoiletpapier
  condition: []
  action:
  - service: shopping_list.add_item
    data:
      name: Toiletpapier
  mode: single
- id: '1699881656417'
  alias: Tag - door tag is scanned
  description: ''
  trigger:
  - platform: event
    event_type: tagscandoor
  condition: []
  action:
  - service: '{% if is_state("alarm_control_panel.alarm", "disarmed") %} script.leaving_house
      {% else %} script.coming_home {% endif %}

      '
  mode: single
- id: '1731669813079'
  alias: Dryer - dryer cycle finished
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.droger_operation_state
    from: run
    to: finished
  conditions: []
  actions:
  - action: notify.parents_phone_app
    metadata: {}
    data:
      title: Droogkast
      message: De droogkast is klaar!
  mode: single
