site_name: Home Assistant setup

theme:
  features:
    - content.tooltips
  font:
    text: Ubuntu Sans
  name: material
  palette:
    primary: blue

repo_name: Home Assistant config
repo_url: https://github.com/claesto/home-assistant

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Introduction: 'index.md'
  - My smart home: 'smarthome.md'
  - Integrations: 'integrations.md'
  - Add-ons: 'addons.md'
  - Dashboards: 'lovelace.md'
  - Automations: 'automations.md'