---
# Garage

automation:
  # Turn on the storage room light
  - alias: 'lighting - storage room - turn on movement and lux < 60'
    id: storage_room_lighting_turn_on_movement_lux_below_60
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        light_target:
          entity_id: light.lamp_berging
        no_motion_wait: 20
        motion_entity_lux: 60
        motion_entity_lux_meter: sensor.hue_motion_sensor_1_illuminance
        motion_entity: binary_sensor.hue_motion_sensor_1_motion