volkswagen_id_start_stop_charging:
  name: Volkswagen ID Start or Stop Charging
  description: Starts or stops charging of Volkswagen ID cars.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: WVGZZZA1ZMP001337
      selector:
        text:
    start_stop:
      name: Start or Stop
      description: Starts or stops charging.
      required: true
      selector:
        select:
          options:
            - "start"
            - "stop"

volkswagen_id_set_climatisation:
  name: Volkswagen ID Set Climatisation
  description: Sets climatisation in Volkswagen ID cars.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: WVGZZZA1ZMP001337
      selector:
        text:
    start_stop:
      name: Start or Stop
      description: Starts or stops climatisation.
      required: true
      selector:
        select:
          options:
            - "start"
            - "stop"
    target_temp:
      name: Target Temperature.
      description: Sets target temperature in celsius.
      required: false
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "ºC"

volkswagen_id_set_target_soc:
  name: Volkswagen ID Set Target SoC
  description: Sets the target SoC in Volkswagen ID cars.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: WVGZZZA1ZMP001337
      selector:
        text:
    target_soc:
      name: Target State of Charge.
      description: Sets state of charge in percentage.
      required: true
      selector:
        number:
          min: 10
          max: 100
          step: 10
          unit_of_measurement: "%"

volkswagen_id_set_ac_charge_speed:
  name: Volkswagen ID Set AC Charge speed
  description: Sets the AC charging speed in Volkswagen ID cars.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: WVGZZZA1ZMP001337
      selector:
        text:
    maximum_reduced:
      name: Maximum or reduced
      description: Maximum (default) charging speed or reduced speed. Actual maximum/reduced speed depends on charging station.
      required: true
      selector:
        select:
          options:
            - "maximum"
            - "reduced"
