blueprint:
  name: Motion-activated Light based on lux reading
  description: Turn on a light when motion is detected, below a certain lux threshold
  domain: automation
  source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

    motion_entity_lux_meter:
      name: Motion Sensor Lux meter
      selector:
        entity:
          device_class: illuminance

    motion_entity_lux:
      name: Motion Sensor Lux
      description: Lux threshold for the motion sensor
      default: 75
      selector:
        number:
          min: 50
          max: 500

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"
condition:
  condition: numeric_state
  entity_id: !input motion_entity_lux_meter
  below: !input motion_entity_lux

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
