esphome:
  name: watermeter
  friendly_name: watermeter

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "JSipcfUbiNIzv5cyNzqpGKZs3xYjwBbi2fUu3uw+vRM="

ota:
  password: "56de1f3f8c35fba5ac55115b80273b3c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watermeter Fallback Hotspot"
    password: "vfEStYtk5WBe"

captive_portal:
    